export const GET_PHOTOS = 'GET_PHOTOS'
export const GET_MORE_PHOTOS = 'GET_MORE_PHOTOS'
export const TOGGLE_LIKE = 'TOGGLE_LIKE'
export const GET_USER = 'GET_USER'
export const GET_AUTH = 'GET_AUTH'
export const GET_CURRENT_PHOTO = 'GET_CURRENT_PHOTO'
export const LOADING_CONTROL = 'LOADING_CONTROL'
export const AUTH_OUT = 'AUTH_OUT'
